### ISSUE TITLE
Fix report generation under JDK 1.7

### ISSUE THREAD

**Issue by lennartj** [mojohaus/aspectj-maven-plugin#2]
Currently, under JDK 7 the CreateReport and CreateSite ITs fail with the same message:

````
> Decorating html files...
> Decorating /home/lj/Development/Projects/Mojohaus/aspectj-maven-plugin/target/it/CreateReport/target/site/aspectj-repo
rt/Azpect.html...
An internal error occured in ajdoc

If this has not already been logged as a bug raised please raise
a new AspectJ bug at https://bugs.eclipse.org/bugs including the
text below. To make the bug a priority, please also include a test
program that can reproduce this problem.

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1904)
        at org.aspectj.tools.ajdoc.HtmlDecorator.decorateHTMLFile(HtmlDecorator.java:272)
        at org.aspectj.tools.ajdoc.HtmlDecorator.decorateHTMLFromIPE(HtmlDecorator.java:122)
        at org.aspectj.tools.ajdoc.HtmlDecorator.decorateHTMLFromIPEs(HtmlDecorator.java:72)
        at org.aspectj.tools.ajdoc.HtmlDecorator.decorateHTMLFromInputFiles(HtmlDecorator.java:62)
        at org.aspectj.tools.ajdoc.Main.decorateHtmlFiles(Main.java:287)
        at org.aspectj.tools.ajdoc.Main.main(Main.java:159)
        at org.codehaus.mojo.aspectj.AjcReportMojo.executeReport(AjcReportMojo.java:280)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:99)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
````

**Comment by davidkarlsen** [comment]
AFAIK this is a problem with aspectj itself: https://bugs.eclipse.org/bugs/show_bug.cgi?id=464604
