### ISSUE TITLE
getting an aspectj compiler error that I don't understand

### ISSUE THREAD

**Issue by andyglick** [mojohaus/aspectj-maven-plugin#23]
Hello,

I am doing a custom build of the Cinnamon webdriver sub-project in github. I am always seeing the same error which has to do with a problem with the aspectj compiler, but I am not sure how to fix it. I do see that a version field is not defined in the Module class but can't sort out why this might be relevant.

The environment is Java 1.8_121, aspect jars 1.8.10, aspectj-maven-plugin 1.9, maven 3.3.9

On the off chance that someone will recognize what the issue might be I'm including the maven output resulting from turning the -e flag on.

If there is any additional information that would be useful to help trouble shoot this problem please let me know and I will deliver it.

Any help that anyone might offer will be appreciated.

Andrews-MBP:webdriver andy$ mvn -e clean compile
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cinnamon-webdriver 0.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cinnamon-webdriver ---
[INFO] 
[INFO] --- aspectj-maven-plugin:1.9:compile (default) @ cinnamon-webdriver ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.109 s
[INFO] Finished at: 2017-03-05T13:22:43-05:00
[INFO] Final Memory: 14M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.9:compile (default) on project cinnamon-webdriver: Unable to parse configuration of mojo org.codehaus.mojo:aspectj-maven-plugin:1.9:compile for parameter version: Cannot find 'version' in class org.codehaus.mojo.aspectj.Module -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.9:compile (default) on project cinnamon-webdriver: Unable to parse configuration of mojo org.codehaus.mojo:aspectj-maven-plugin:1.9:compile for parameter version: Cannot find 'version' in class org.codehaus.mojo.aspectj.Module
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo org.codehaus.mojo:aspectj-maven-plugin:1.9:compile for parameter version: Cannot find 'version' in class org.codehaus.mojo.aspectj.Module
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:662)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:594)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find 'version' in class org.codehaus.mojo.aspectj.Module
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:252)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:57)
	at org.codehaus.plexus.component.configurator.converters.composite.AbstractCollectionConverter.fromChildren(AbstractCollectionConverter.java:54)
	at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromConfiguration(ArrayConverter.java:52)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty(CompositeBeanHelper.java:273)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:210)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:34)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:632)
	... 23 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException

**Comment by davidkarlsen** [comment]
Hmm, not sure - could you provide a stripped-down project? Also can you try the latest release or the 1.11.1-SNAPSHOT?

**Comment by davidkarlsen** [comment]
@andyglick Did the latest release help?

**Comment by davidkarlsen** [comment]
Could you also share your <configuration> section?

**Comment by pothuganti19** [comment]
Hi, Is this resolved? I am facing same issue 

<configuration>
		          <weaveDependencies>
		            <weaveDependency>
		    			<groupId>com.adyen</groupId>
    					<artifactId>xxxx-java-api-library</artifactId>
    					<version>2.7.2</version>
    		        </weaveDependency>

		          </weaveDependencies>
		        </configuration>

**Comment by pothuganti19** [comment]
<configuration>
		          <weaveDependencies>
		            <weaveDependency>
		    			<groupId>com.adyen</groupId>
    					<artifactId>xxx-java-api-library</artifactId>
    					<version>2.7.2</version>
    		        </weaveDependency>

		          </weaveDependencies>
		        </configuration>
